- name: Copy docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: /home/ubuntu/docker-compose.yml

- name: Run frontend container
  docker_compose:
    project_src: /home/ubuntu
    state: present
    pull: yes
