- name: Copy docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: /home/ubuntu/docker-compose.yml

- name: Run database container
  command: docker compose up -d
  args:
    chdir: /home/ubuntu
