---
- name: Provision infrastructure with Terraform
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: ../terraform

    - name: Terraform deployment Plan
      command: terraform plan
      args:
        chdir: ../terraform

    - name: Apply Terraform
      command: terraform apply -auto-approve
      args:
        chdir: ../terraform

    - name: Get Terraform outputs
      command: terraform output -json
      args:
        chdir: ../terraform
      register: tf_output

    - name: Parse outputs from Terraform
      set_fact:
        tf: "{{ tf_output.stdout | from_json }}"

    - name: Add hosts dynamically from Terraform outputs
      add_host:
        name: "{{ item.name }}"
        groups: "{{ item.group }}"
        ansible_host: "{{ item.ip }}"
        ansible_user: ubuntu
        ansible_ssh_private_key_file: "{{ ssh_key_path }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ item.ssh_args | default('') }}"
      loop:
        - name: frontend
          group: frontend
          ip: "{{ tf.frontend_public_ip.value }}"
        - name: backend
          group: backend
          ip: "{{ tf.backend_private_ip.value }}"
          ssh_args: "-o ProxyCommand='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i {{ ssh_key_path }} -W %h:%p ubuntu@{{ tf.frontend_public_ip.value }}'"
        - name: database
          group: database
          ip: "{{ tf.database_private_ip.value }}"
          ssh_args: "-o ProxyCommand='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i {{ ssh_key_path }} -W %h:%p ubuntu@{{ tf.frontend_public_ip.value }}'"

- name: Configure all nodes
  hosts: frontend:backend:database
  become: true
  roles:
    - common

- name: Configure frontend node
  hosts: frontend
  become: true
  roles:
    - frontend

- name: Configure backend node
  hosts: backend
  become: true
  roles:
    - backend

- name: Configure database node
  hosts: database
  become: true
  roles:
    - database

